### ISSUE TITLE
Need pollInterval to feedback status on ZigBee Device

### ISSUE THREAD

**Issue by kevinhab** [athombv/node-homey-meshdriver#123]
Hi All,
I 'm build an app for ZigBee Device.
If it want to update status from ZigBee Device, it must have **pollInterval** function (don't have pollInterval function, no feedback status ZigBee Device)
Example code:
`const ZigBeeDevice = require('homey-meshdriver').ZigBeeDevice;`

`class WallSwitch2 extends ZigBeeDevice {`

	async onMeshInit() {

		// Register onoff.1 capability
		this.registerCapability('onoff.1', 'genOnOff', {
			getOpts: {
				getOnStart: true,
				pollInterval: 2000,
			},
			endpoint: 0
		});
		
		// Register onoff.2 capability
		this.registerCapability('onoff.2', 'genOnOff', {
			getOpts: {
				getOnStart: true,
				pollInterval: 2100,
			},
			endpoint: 2
		});
	}
}

`module.exports = WallSwitch2;`

But insert **pollInterval** function, it'll make app slowly or unstable when there are many ZigBee devices.
Could anyone please fix this issue?

**Comment by RobinBol** [comment]
A poll interval of 2 sec is very aggressive, no wonder your app/devices become unstable. Please increase the poll interval to a decent level and try again. It is generally not advised to implement devices that require (heavy) polling, since this becomes quite a burden on the network, especially when a user adds multiple of these devices. It is better to look into `registerAttrReportListener`, since I can't image a ZigBee device not reporting its `onoff` state to the controller when it changes.
