### ISSUE TITLE
Forced_timout when no response from zigbee device

### ISSUE THREAD

**Issue by prj84** [athombv/node-homey-meshdriver#99]
Hi I have written the Elko app for Homey. I have a problem with the dimmer device that it do not respond back when you send commands. (all commands sent goes through).  This seems to be a device issue. The Device Handler for SmartThings ignore this and just read status change through the att reader.

Is there any way to turn off the the need for a respons/promise when using the set commands?

All att. readings from device work with no problem!

**Comment by RobinBol** [comment]
This is possible, but you would have to write the implementation from scratch (not using the MeshDriver ZigBee device). Something like the quick sketch below:

```
class MyDevice extends Homey.Device {

	// this method is called when the Device is inited
	onInit() {

		// register a capability listener
		this.registerCapabilityListener('onoff', this.onCapabilityOnoff.bind(this))
	}

	// this method is called when the Device has requested a state change (turned on or off)
	onCapabilityOnoff( value, opts, callback ) {

		// return promise, ignore
		this.node.endpoints[0].clusters['genLevelCtrl'].do("moveToLevelWithOnOff", {level: 255, transtime: 1});
		
		// return resolved promise
		return Promise.resolve( );
	}

}
```

I will close this issue, since as you said yourself, it is a problem with your device, and a work around is available, therefore it is more a dev support issue. If you need further help, also checkout the #developers channel on our community Slack!
